apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-secrets-reader
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-read-secrets-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-secrets-reader
  apiGroup: rbac.authorization.k8s.io
